# Generated by Django 3.1.4 on 2021-01-22 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('release_date', models.DateTimeField(verbose_name='Date de Sortie')),
                ('vote', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('realisator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmotek.realisator', verbose_name='Réalisateur')),
            ],
        ),
    ]
