# Generated by Django 3.1.4 on 2021-01-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmotek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='score',
        ),
        migrations.AlterField(
            model_name='film',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
