# Generated by Django 3.1.4 on 2021-01-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmotek', '0002_auto_20210123_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='vote',
        ),
    ]
